"use client";

import { useState } from "react";
import jsPDF from "jspdf";

type Item = {
  name: string;
  qty: number;
  unit: string;
  rate: number;
};

export default function Home() {
  const [showForm, setShowForm] = useState(false);
  const [generated, setGenerated] = useState(false);

  const [customer, setCustomer] = useState("");
  const [phone, setPhone] = useState("");
  const [location, setLocation] = useState("");
  const [job, setJob] = useState("");

  const [items, setItems] = useState<Item[]>([]);

  // Generate quotation
  const generateQuotation = () => {
    if (!customer || !job) {
      alert("Please enter customer name and job description.");
      return;
    }

    // Temporary AI-style quotation logic.
    // We will connect a real AI API later.
    const generatedItems: Item[] = [
      {
        name: "Wall preparation",
        qty: 950,
        unit: "sq.ft",
        rate: 8,
      },
      {
        name: "Primer application",
        qty: 950,
        unit: "sq.ft",
        rate: 12,
      },
      {
        name: "Interior paint - 2 coats",
        qty: 950,
        unit: "sq.ft",
        rate: 18,
      },
      {
        name: "Labour",
        qty: 1,
        unit: "job",
        rate: 12000,
      },
    ];

    setItems(generatedItems);
    setGenerated(true);
  };

  // Download quotation as PDF
  const downloadPDF = () => {
    const doc = new jsPDF();

    // QuoteKaro heading
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("QuoteKaro", 20, 20);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Professional Quotation", 20, 28);

    // Customer details
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Customer Details", 20, 42);

    doc.setFont("helvetica", "normal");
    doc.text(`Customer: ${customer}`, 20, 50);
    doc.text(`Phone: ${phone || "Not provided"}`, 20, 57);
    doc.text(`Location: ${location || "Not provided"}`, 20, 64);

    // Table heading
    let y = 80;

    doc.setFont("helvetica", "bold");
    doc.text("Item", 20, y);
    doc.text("Qty", 110, y);
    doc.text("Rate", 135, y);
    doc.text("Amount", 165, y);

    doc.setFont("helvetica", "normal");

    // Items
    y += 8;

    items.forEach((item) => {
      const amount = item.qty * item.rate;

      doc.text(item.name, 20, y);
      doc.text(`${item.qty} ${item.unit}`, 110, y);
      doc.text(`Rs. ${item.rate.toLocaleString("en-IN")}`, 135, y);
      doc.text(
        `Rs. ${amount.toLocaleString("en-IN")}`,
        165,
        y
      );

      y += 8;
    });

    // Totals
    y += 5;

    doc.line(20, y, 190, y);

    y += 10;

    doc.text(
      `Subtotal: Rs. ${subtotal.toLocaleString("en-IN")}`,
      120,
      y
    );

    y += 8;

    doc.text(
      `GST (18%): Rs. ${gst.toLocaleString("en-IN", {
        maximumFractionDigits: 0,
      })}`,
      120,
      y
    );

    y += 10;

    doc.setFont("helvetica", "bold");

    doc.text(
      `Total: Rs. ${total.toLocaleString("en-IN", {
        maximumFractionDigits: 0,
      })}`,
      120,
      y
    );

    // Footer
    y += 20;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by QuoteKaro", 20, y);

    // Download
    doc.save(
      `QuoteKaro-${customer.replace(/\s+/g, "-") || "quotation"}.pdf`
    );
  };

  // Calculate totals
  const subtotal = items.reduce(
    (total, item) => total + item.qty * item.rate,
    0
  );

  const gst = subtotal * 0.18;
  const total = subtotal + gst;

  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      {/* Header */}
      <header className="border-b bg-white">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5">
          <div>
            <h1 className="text-2xl font-bold">
              Quote<span className="text-blue-600">Karo</span>
            </h1>

            <p className="text-sm text-slate-500">
              AI business assistant for contractors
            </p>
          </div>

          <button
            onClick={() => {
              setShowForm(true);
              setGenerated(false);
            }}
            className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white shadow-sm hover:bg-blue-700"
          >
            + New quotation
          </button>
        </div>
      </header>

      <div className="mx-auto grid max-w-7xl grid-cols-1 gap-6 px-6 py-8 lg:grid-cols-[220px_1fr]">
        {/* Sidebar */}
        <aside className="rounded-2xl border bg-white p-4">
          <nav className="space-y-2">
            <button className="w-full rounded-xl bg-blue-50 px-4 py-3 text-left font-semibold text-blue-700">
              ▦ Dashboard
            </button>

            <button
              onClick={() => setShowForm(true)}
              className="w-full rounded-xl px-4 py-3 text-left hover:bg-slate-50"
            >
              ＋ New quotation
            </button>

            <button className="w-full rounded-xl px-4 py-3 text-left hover:bg-slate-50">
              ♙ Customers
            </button>

            <button className="w-full rounded-xl px-4 py-3 text-left hover:bg-slate-50">
              ▤ Quotations
            </button>

            <button className="w-full rounded-xl px-4 py-3 text-left hover:bg-slate-50">
              ₹ Payments
            </button>

            <div className="my-5 border-t" />

            <button className="w-full rounded-xl px-4 py-3 text-left hover:bg-slate-50">
              ⚙ Settings
            </button>
          </nav>

          <div className="mt-8 rounded-xl bg-slate-50 p-4">
            <p className="text-xs text-slate-500">YOUR BUSINESS</p>
            <p className="mt-1 font-semibold">Free plan</p>
          </div>
        </aside>

        {/* Main */}
        <section>
          {!showForm ? (
            <>
              {/* Welcome */}
              <div className="mb-6">
                <p className="text-sm text-slate-500">
                  Thursday, September 10
                </p>

                <div className="mt-1 flex items-center justify-between">
                  <h2 className="text-3xl font-bold">
                    Good evening 👋
                  </h2>
                </div>
              </div>

              {/* Hero */}
              <div className="rounded-3xl bg-slate-950 p-8 text-white shadow-lg">
                <div className="max-w-3xl">
                  <span className="rounded-full bg-blue-600/30 px-4 py-2 text-sm font-medium text-blue-300">
                    ✨ AI-powered quotations
                  </span>

                  <h2 className="mt-5 text-3xl font-bold md:text-4xl">
                    Create professional quotations in seconds.
                  </h2>

                  <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">
                    Describe the job in simple language. QuoteKaro turns
                    your requirements into a professional quotation.
                  </p>

                  <button
                    onClick={() => setShowForm(true)}
                    className="mt-7 rounded-xl bg-white px-6 py-3 font-bold text-slate-950 hover:bg-slate-100"
                  >
                    Create your first quote →
                  </button>
                </div>
              </div>

              {/* Stats */}
              <div className="mt-6 grid gap-4 md:grid-cols-4">
                <Stat
                  title="Total quotations"
                  value="1"
                  subtitle="This month"
                />

                <Stat
                  title="Accepted quotes"
                  value="0"
                  subtitle="This month"
                />

                <Stat
                  title="Pending payments"
                  value="₹0"
                  subtitle="Outstanding"
                />

                <Stat
                  title="Revenue"
                  value="₹0"
                  subtitle="This month"
                />
              </div>

              {/* Feature cards */}
              <div className="mt-6 grid gap-4 md:grid-cols-3">
                <Feature
                  icon="✨"
                  title="AI Quotation"
                  text="Turn a simple job description into an itemized quote."
                />

                <Feature
                  icon="₹"
                  title="Smart Pricing"
                  text="Suggest labour and material pricing for your jobs."
                />

                <Feature
                  icon="📄"
                  title="Professional PDF"
                  text="Generate a quotation ready to send to your customer."
                />
              </div>
            </>
          ) : (
            <>
              {/* New quotation form */}
              <button
                onClick={() => setShowForm(false)}
                className="mb-5 text-sm font-semibold text-blue-600"
              >
                ← Back to dashboard
              </button>

              <div className="mb-6">
                <p className="text-sm text-slate-500">
                  QuoteKaro
                </p>

                <h2 className="mt-1 text-3xl font-bold">
                  Create new quotation
                </h2>

                <p className="mt-2 text-slate-500">
                  Tell us about the customer and the job. QuoteKaro will
                  prepare the quotation.
                </p>
              </div>

              <div className="grid gap-6 lg:grid-cols-2">
                {/* Form */}
                <div className="rounded-2xl border bg-white p-6 shadow-sm">
                  <h3 className="text-lg font-bold">
                    Customer details
                  </h3>

                  <div className="mt-5 space-y-4">
                    <Input
                      label="Customer name"
                      placeholder="e.g. Rahul Sharma"
                      value={customer}
                      onChange={setCustomer}
                    />

                    <Input
                      label="Phone number"
                      placeholder="e.g. 9876543210"
                      value={phone}
                      onChange={setPhone}
                    />

                    <Input
                      label="Project location"
                      placeholder="e.g. Wakad, Pune"
                      value={location}
                      onChange={setLocation}
                    />

                    <div>
                      <label className="mb-2 block text-sm font-semibold">
                        Describe the job
                      </label>

                      <textarea
                        value={job}
                        onChange={(e) => setJob(e.target.value)}
                        placeholder="Example: 2BHK painting in Wakad, around 950 sq ft. Need wall preparation, primer and two coats of interior paint. Complete within 7 days."
                        className="h-40 w-full resize-none rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
                      />
                    </div>

                    <button
                      onClick={generateQuotation}
                      className="w-full rounded-xl bg-blue-600 py-4 font-bold text-white hover:bg-blue-700"
                    >
                      ✨ Generate quotation
                    </button>
                  </div>
                </div>

                {/* Preview */}
                <div className="rounded-2xl border bg-white p-6 shadow-sm">
                  {!generated ? (
                    <div className="flex h-full min-h-[400px] flex-col items-center justify-center text-center">
                      <div className="text-5xl">✨</div>

                      <h3 className="mt-5 text-xl font-bold">
                        Your quotation will appear here
                      </h3>

                      <p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">
                        Enter the job details and click “Generate
                        quotation” to create an itemized quotation.
                      </p>
                    </div>
                  ) : (
                    <QuotationPreview
                      customer={customer}
                      phone={phone}
                      location={location}
                      items={items}
                      subtotal={subtotal}
                      gst={gst}
                      total={total}
                      onDownloadPDF={downloadPDF}
                    />
                  )}
                </div>
              </div>
            </>
          )}
        </section>
      </div>
    </main>
  );
}

/* ---------- Components ---------- */

function Stat({
  title,
  value,
  subtitle,
}: {
  title: string;
  value: string;
  subtitle: string;
}) {
  return (
    <div className="rounded-2xl border bg-white p-5 shadow-sm">
      <p className="text-sm text-slate-500">{title}</p>

      <p className="mt-3 text-2xl font-bold">
        {value}
      </p>

      <p className="mt-1 text-xs text-slate-400">
        {subtitle}
      </p>
    </div>
  );
}

function Feature({
  icon,
  title,
  text,
}: {
  icon: string;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-2xl border bg-white p-6 shadow-sm">
      <div className="text-3xl">{icon}</div>

      <h3 className="mt-4 font-bold">
        {title}
      </h3>

      <p className="mt-2 text-sm leading-6 text-slate-500">
        {text}
      </p>
    </div>
  );
}

function Input({
  label,
  placeholder,
  value,
  onChange,
}: {
  label: string;
  placeholder: string;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <div>
      <label className="mb-2 block text-sm font-semibold">
        {label}
      </label>

      <input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
      />
    </div>
  );
}

function QuotationPreview({
  customer,
  phone,
  location,
  items,
  subtotal,
  gst,
  total,
  onDownloadPDF,
}: {
  customer: string;
  phone: string;
  location: string;
  items: Item[];
  subtotal: number;
  gst: number;
  total: number;
  onDownloadPDF: () => void;
}) {
  return (
    <div>
      {/* Preview header */}
      <div className="flex items-start justify-between border-b pb-5">
        <div>
          <h3 className="text-2xl font-bold">
            Quote<span className="text-blue-600">Karo</span>
          </h3>

          <p className="mt-1 text-sm text-slate-500">
            Professional quotation
          </p>
        </div>

        <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">
          DRAFT
        </span>
      </div>

      {/* Customer information */}
      <div className="grid gap-4 py-5 sm:grid-cols-2">
        <div>
          <p className="text-xs font-semibold uppercase text-slate-400">
            Customer
          </p>

          <p className="mt-1 font-semibold">
            {customer}
          </p>

          {phone && (
            <p className="text-sm text-slate-500">
              {phone}
            </p>
          )}
        </div>

        <div>
          <p className="text-xs font-semibold uppercase text-slate-400">
            Project location
          </p>

          <p className="mt-1 font-semibold">
            {location || "Not provided"}
          </p>
        </div>
      </div>

      {/* Items table */}
      <div className="overflow-hidden rounded-xl border">
        <table className="w-full text-sm">
          <thead className="bg-slate-50">
            <tr>
              <th className="px-3 py-3 text-left">
                Item
              </th>

              <th className="px-3 py-3 text-right">
                Qty
              </th>

              <th className="px-3 py-3 text-right">
                Rate
              </th>

              <th className="px-3 py-3 text-right">
                Amount
              </th>
            </tr>
          </thead>

          <tbody>
            {items.map((item, index) => (
              <tr key={index} className="border-t">
                <td className="px-3 py-3">
                  <p className="font-medium">
                    {item.name}
                  </p>

                  <p className="text-xs text-slate-400">
                    {item.unit}
                  </p>
                </td>

                <td className="px-3 py-3 text-right">
                  {item.qty}
                </td>

                <td className="px-3 py-3 text-right">
                  ₹{item.rate.toLocaleString("en-IN")}
                </td>

                <td className="px-3 py-3 text-right font-medium">
                  ₹{(item.qty * item.rate).toLocaleString(
                    "en-IN"
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Totals */}
      <div className="mt-5 space-y-2 border-t pt-5 text-sm">
        <div className="flex justify-between">
          <span className="text-slate-500">
            Subtotal
          </span>

          <span>
            ₹{subtotal.toLocaleString("en-IN")}
          </span>
        </div>

        <div className="flex justify-between">
          <span className="text-slate-500">
            GST (18%)
          </span>

          <span>
            ₹{gst.toLocaleString("en-IN", {
              maximumFractionDigits: 0,
            })}
          </span>
        </div>

        <div className="flex justify-between border-t pt-3 text-lg font-bold">
          <span>Total</span>

          <span className="text-blue-600">
            ₹{total.toLocaleString("en-IN", {
              maximumFractionDigits: 0,
            })}
          </span>
        </div>
      </div>

      {/* Action buttons */}
      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        <button
          onClick={onDownloadPDF}
          className="rounded-xl border border-slate-300 py-3 font-semibold hover:bg-slate-50"
        >
          📄 Download PDF
        </button>

        <button
          onClick={() =>
            alert("WhatsApp sharing will be added next.")
          }
          className="rounded-xl bg-green-600 py-3 font-semibold text-white hover:bg-green-700"
        >
          💬 Share on WhatsApp
        </button>
      </div>
    </div>
  );
}